### PR TITLE
Add missing extern declarations in header files

### PR DESCRIPTION
**Pull request by rbrune**
This allows building with modern more strict compilers e.g. gcc 10

### CODE REVIEW

**Comment by KajiTetsushi** [comment]
@rbrune Sorry about this one, too. What results do I need to compare with this PR on my machines? (i.e. macOS, Windows)

Using the latest Xcode 11.7 hasn't shown any issues on my end yet on `main` branch. Do I have to upgrade my machine's `gcc`?

**Comment by thesamesam** [comment]
@KajiTetsushi You can emulate this GCC 10 behaviour with CFLAGS="-fno-common" on e.g. GCC 9.

You should get a bunch of "multiple definitions of..." errors.

**Comment by KajiTetsushi** [comment]
Hey, @thesamesam @rbrune, going back to this again: am I right to assume that this fix is meant to address issues happening with `gcc` on Linux?

On macOS, [instructions is to use Xcode](https://github.com/KajiTetsushi/HomeworldSDL/tree/main/Mac), it's `llvm`/`clang` when I run `gcc --version`:
```sh
gcc --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

As far as I've learned, on macOS, LLVM has been the way forward and has supplanted compiling and debugging on Xcode ever since. My references:
1. https://apple.stackexchange.com/questions/174231/what-is-difference-between-gcc-version-and-xcode-gcc-version#comment205137_174231
2. https://apple.stackexchange.com/questions/308830/why-does-g-version-say-llvm-clang#comment391057_308833
3. https://stackoverflow.com/a/8707446
4. https://useyourloaf.com/blog/compiler-options-in-xcode-gcc-or-llvm/

----
> **NOTE:** If the following makes absolutely no sense because it needs to be strictly on Linux, please correct me.

Now, I can go even further and try the Linux build on macOS.

What I've done so far was this.
1. Install GCC, then alias it over LLVM temporarily. ([reference](https://apple.stackexchange.com/a/99157))
    a. `brew install gcc` => `gcc 10.2.0`
    b. `alias gcc="<path_to_gcc_bin>"` to my `.bash_profile`
2. Install SDL2 development libraries and headers, not the framework. ([reference](https://discourse.libsdl.org/t/need-help-compiling-against-framework-mac-osx/22808/2))
    a. `brew install sdl2` => `sdl 2.0.14`
3. Run the Linux procedure.
    ```sh
    cd Linux
    ./bootstrap 
    ../configure # Unfortunately, this is where I'm stuck.
    make
    ```

This is what `../configure` tells me. I don't have much on Google search to tell me anything.
```sh
checking for glBegin in -lGL... no
checking for glEnableClientState in -lGLES_CM... no
checking for main in -lopengl32... no
configure: error: *** Found neither -lGL nor -lGLES_CM !
```

**Comment by KajiTetsushi** [comment]
@rbrune as per your feedback in our Discord, the build runs fine on macOS locally. Unless Windows needs this, too, I assume we're all good...

**Review by KajiTetsushi — APPROVED** [review]

**Pull request merged**
